// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fUUerClAYIOU2BhhqpW2naSloesbKCY',
    appId: '1:851148683967:web:a1bb673fcd9b3cbace240a',
    messagingSenderId: '851148683967',
    projectId: 'foodpanda-de39a',
    authDomain: 'foodpanda-de39a.firebaseapp.com',
    storageBucket: 'foodpanda-de39a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsjl-WohUvfEcAqlpCcXF3bRjcVEJohY',
    appId: '1:851148683967:android:a4a4d373b11f07e1ce240a',
    messagingSenderId: '851148683967',
    projectId: 'foodpanda-de39a',
    storageBucket: 'foodpanda-de39a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyE-QIk_bpnV7MMCL2xyACGyAHqvSn6Y',
    appId: '1:851148683967:ios:212970305abf0874ce240a',
    messagingSenderId: '851148683967',
    projectId: 'foodpanda-de39a',
    storageBucket: 'foodpanda-de39a.firebasestorage.app',
    iosBundleId: 'com.example.foodpanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXyE-QIk_bpnV7MMCL2xyACGyAHqvSn6Y',
    appId: '1:851148683967:ios:212970305abf0874ce240a',
    messagingSenderId: '851148683967',
    projectId: 'foodpanda-de39a',
    storageBucket: 'foodpanda-de39a.firebasestorage.app',
    iosBundleId: 'com.example.foodpanda',
  );
}
